<?xml version="1.0" encoding="UTF-8"?>
<!-- NetBeans build script for AVLTreeVisualizador -->
<project name="AVLTreeVisualizador" default="default" basedir=".">
    <description>Builds, tests, and runs the project AVLTreeVisualizador.</description>
    <import file="nbproject/build-impl.xml"/>
</project>
